// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-image-importer/api"
	"sync"
)

var (
	lockImageAPIClienterMockChecker sync.RWMutex
)

// Ensure, that ImageAPIClienterMock does implement ImageAPIClienter.
// If this is not the case, regenerate this file with moq.
var _ api.ImageAPIClienter = &ImageAPIClienterMock{}

// ImageAPIClienterMock is a mock implementation of api.ImageAPIClienter.
//
//     func TestSomethingThatUsesImageAPIClienter(t *testing.T) {
//
//         // make and configure a mocked api.ImageAPIClienter
//         mockedImageAPIClienter := &ImageAPIClienterMock{
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//         }
//
//         // use mockedImageAPIClienter in code that requires api.ImageAPIClienter
//         // and then make assertions.
//
//     }
type ImageAPIClienterMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
	}
}

// Checker calls CheckerFunc.
func (mock *ImageAPIClienterMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("ImageAPIClienterMock.CheckerFunc: method is nil but ImageAPIClienter.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockImageAPIClienterMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockImageAPIClienterMockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedImageAPIClienter.CheckerCalls())
func (mock *ImageAPIClienterMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockImageAPIClienterMockChecker.RLock()
	calls = mock.calls.Checker
	lockImageAPIClienterMockChecker.RUnlock()
	return calls
}
