// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-image-importer/api"
	"sync"
)

var (
	lockKafkaConsumerMockChecker                 sync.RWMutex
	lockKafkaConsumerMockClose                   sync.RWMutex
	lockKafkaConsumerMockStopListeningToConsumer sync.RWMutex
)

// Ensure, that KafkaConsumerMock does implement KafkaConsumer.
// If this is not the case, regenerate this file with moq.
var _ api.KafkaConsumer = &KafkaConsumerMock{}

// KafkaConsumerMock is a mock implementation of api.KafkaConsumer.
//
//     func TestSomethingThatUsesKafkaConsumer(t *testing.T) {
//
//         // make and configure a mocked api.KafkaConsumer
//         mockedKafkaConsumer := &KafkaConsumerMock{
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             CloseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Close method")
//             },
//             StopListeningToConsumerFunc: func(ctx context.Context) error {
// 	               panic("mock out the StopListeningToConsumer method")
//             },
//         }
//
//         // use mockedKafkaConsumer in code that requires api.KafkaConsumer
//         // and then make assertions.
//
//     }
type KafkaConsumerMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// StopListeningToConsumerFunc mocks the StopListeningToConsumer method.
	StopListeningToConsumerFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// StopListeningToConsumer holds details about calls to the StopListeningToConsumer method.
		StopListeningToConsumer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
}

// Checker calls CheckerFunc.
func (mock *KafkaConsumerMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("KafkaConsumerMock.CheckerFunc: method is nil but KafkaConsumer.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockKafkaConsumerMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockKafkaConsumerMockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedKafkaConsumer.CheckerCalls())
func (mock *KafkaConsumerMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockKafkaConsumerMockChecker.RLock()
	calls = mock.calls.Checker
	lockKafkaConsumerMockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *KafkaConsumerMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("KafkaConsumerMock.CloseFunc: method is nil but KafkaConsumer.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockKafkaConsumerMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockKafkaConsumerMockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedKafkaConsumer.CloseCalls())
func (mock *KafkaConsumerMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockKafkaConsumerMockClose.RLock()
	calls = mock.calls.Close
	lockKafkaConsumerMockClose.RUnlock()
	return calls
}

// StopListeningToConsumer calls StopListeningToConsumerFunc.
func (mock *KafkaConsumerMock) StopListeningToConsumer(ctx context.Context) error {
	if mock.StopListeningToConsumerFunc == nil {
		panic("KafkaConsumerMock.StopListeningToConsumerFunc: method is nil but KafkaConsumer.StopListeningToConsumer was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockKafkaConsumerMockStopListeningToConsumer.Lock()
	mock.calls.StopListeningToConsumer = append(mock.calls.StopListeningToConsumer, callInfo)
	lockKafkaConsumerMockStopListeningToConsumer.Unlock()
	return mock.StopListeningToConsumerFunc(ctx)
}

// StopListeningToConsumerCalls gets all the calls that were made to StopListeningToConsumer.
// Check the length with:
//     len(mockedKafkaConsumer.StopListeningToConsumerCalls())
func (mock *KafkaConsumerMock) StopListeningToConsumerCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockKafkaConsumerMockStopListeningToConsumer.RLock()
	calls = mock.calls.StopListeningToConsumer
	lockKafkaConsumerMockStopListeningToConsumer.RUnlock()
	return calls
}
